name: Login and push nexus

on:
  push:
    branches:
      - main

jobs:
  login-and-push:
    runs-on: ubuntu-latest
    steps:
      - name: Configure Docker for insecure registry
        run: |
          # Crea el archivo de configuración de Docker para permitir la conexión HTTP a tu Nexus
          echo '{"insecure-registries": ["${{ secrets.NEXUS_DOCKER_REPO_URL }}"]}' | sudo tee /etc/docker/daemon.json
          # Reinicia el servicio de Docker para que aplique la nueva configuración
          sudo systemctl docker restart

      - name: Log in to Nexus
        uses: docker/login-action@v3
        with:
          registry: ${{ secrets.NEXUS_DOCKER_REPO_URL }}
          username: ${{ secrets.NEXUS_USERNAME }}
          password: ${{ secrets.NEXUS_PASSWORD }}

      - name: Build and push Docker image
        uses: docker/build-push-action@v5
        with:
          context: .
          push: true
          tags: |
            ${{ secrets.NEXUS_DOCKER_REPO_URL }}/fastapi-store-app:latest
            ${{ secrets.NEXUS_DOCKER_REPO_URL }}/fastapi-store-app:${{ github.sha }}