name: Login and push nexus

on:
  workflow_run:
    workflows: ["CI/CD + Deploy en EC2 (Amazon Linux)"]  # Nombre del primer workflow
    types:
      - completed  # Se ejecutará cuando el primer pipeline termine

jobs:
  login-and-push:
    runs-on: ubuntu-latest
    steps:
      - name: Configurar Docker para usar Nexus por HTTP
        run: |
          echo "{ \"insecure-registries\": [\"${{ secrets.NEXUS_DOCKER_REPO_URL }}\"] }" | sudo tee /etc/docker/daemon.json
          sudo systemctl restart docker

      - name: Log in to Nexus
        uses: docker/login-action@v3
        with:
          registry: ${{ secrets.NEXUS_DOCKER_REPO_URL }}
          username: ${{ secrets.NEXUS_USERNAME }}
          password: ${{ secrets.NEXUS_PASSWORD }}
      
      - name: Esperar configuracion
        run: |
          echo "Esperando 60 segundos antes de continuar..."
          sleep 60  # Espera de 60 segundos para asegurar la sincronización

      - name: Construir y subir imagen a Nexus
        uses: docker/build-push-action@v5
        with:
          context: .
          push: true
          tags: |
            ${{ secrets.NEXUS_DOCKER_REPO_URL }}/fastapi-docker/fastapi-app:latest
            ${{ secrets.NEXUS_DOCKER_REPO_URL }}/fastapi-store-app:${{ github.sha }}
